<a href="https://colab.research.google.com/github/Vikas-1093/Data-science/blob/main/23_FDSLab1Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!ls sample_data

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


In [2]:
print("hello")

hello


In [3]:
a = 4
b = 6
print('a = '+str(a) + ' & b = '+str(b))

a = 4 & b = 6


In [4]:
type(a)

int

In [5]:
s1 = "RJ College"
type(s1)

str

In [6]:
pi = 3.145
type(pi)

float


**Markdown Guide Practice**

**Equations**

$y = x^2$

$e^{i\pi} + 1 = 0$


$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$


$\frac{n!}{k!(n-k)!} = {n \choose k}$


$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} &amp; a_{1,2} &amp; \cdots &amp; a_{1,n} \\
  a_{2,1} &amp; a_{2,2} &amp; \cdots &amp; a_{2,n} \\
  \vdots  &amp; \vdots  &amp; \ddots &amp; \vdots  \\
  a_{m,1} &amp; a_{m,2} &amp; \cdots &amp; a_{m,n}
 \end{pmatrix}$

**NumPy**

https://numpy.org/doc/stable/user/whatisnumpy.html

In [7]:
a = [1,2,3]
a

[1, 2, 3]

In [8]:
type(a)


list

In [9]:
b = [4,5,6]
b

[4, 5, 6]

In [10]:
#Multiplication
c = []
for i in range(len(a)):
  c.append(a[i]*b[i])
c

[4, 10, 18]

In [11]:
#Addition of two array
c = []
for i in range(len(a)):
  c.append(a[i]+b[i])
c

[5, 7, 9]

In [13]:
import time
print("Sleeping")
time.sleep(30) # sleep for a while; interrupt me!
print("Done Sleeping")

Sleeping
Done Sleeping


In [15]:
import numpy as np

In [16]:
#define automatic array
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
a.ndim

2

In [19]:
a.dtype

dtype('int64')

In [21]:
a.dtype.name

'int64'

In [22]:
#itemsize = row + column
a.itemsize

8

In [23]:
#size = total no. of elements in the array
a.size

15

In [25]:
type(a)

numpy.ndarray

In [26]:
#define array manually
b = np.array([[12,13,14],[15,16,17]])
b

array([[12, 13, 14],
       [15, 16, 17]])

In [27]:
#reshape the manual array using 'reshape'

c = b.reshape(3,2)
c

array([[12, 13],
       [14, 15],
       [16, 17]])

In [28]:
#Create an array of 10 characters with 2 rows and 5 columns
d = np.array(['p','a','v','a','n','y','a','d','a','v'])
s = d.reshape(2,5)
s

array([['p', 'a', 'v', 'a', 'n'],
       ['y', 'a', 'd', 'a', 'v']], dtype='<U1')